[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.clear-plugin-dir]
script_runner = "@duckscript"
script = """
rm -r ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hdHebi
"""

[tasks.build-plugin]
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hebi/hebi-hydra"
command = "cargo"
args = ["build", "--release"]
env = { PXR_LIB_PREFIX = "libpxr_" }

[tasks.make-plugin-dir]
dependencies = ["clear-plugin-dir"]
script_runner = "@duckscript"
script = """
PLUGIN_DIR = set ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hdHebi
mkdir ${PLUGIN_DIR}
mkdir ${PLUGIN_DIR}/resources
"""

[tasks.copy-plugin-files]
dependencies = ["make-plugin-dir", "build-plugin"]
script_runner = "@duckscript"
script = """
TARGET_DIR = set ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hebi/target
PLUGIN_DIR = set ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hdHebi
glob_cp ${TARGET_DIR}/release/*.dll ${PLUGIN_DIR}
glob_cp ${TARGET_DIR}/release/*.so ${PLUGIN_DIR}
glob_cp hebi/resources/* ${PLUGIN_DIR}/resources/
"""

[tasks.clean-hydra-bridge]
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hydra-bridge"
command = "cargo"
args = ["clean"]

[tasks.clean-hebi]
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hebi"
command = "cargo"
args = ["clean"]

[tasks.clean]
dependencies = ["clean-hydra-bridge", "clean-hebi"]

[tasks.default]
dependencies = ["copy-plugin-files"]
