[package]
name = "hebi-hydra"

version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
hydra-bridge = { path = "../../hydra-bridge/hydra-bridge" }
parking_lot = { workspace = true }
